### ISSUE TITLE
Code reorganisation on Body-modeling-Xyioyun branch

### ISSUE THREAD

**Issue by ThoChat** [ThoChat/jupedsim#6]
This issues is to report the modification made to adapt the code that have been implemented by Xyioyun Matlab code to control humanoid body motion associated with gait.

**Comment by ThoChat** [comment]
Things to do:
- Give explicit names to all variables and functions
- Use Eigen library to perform matrix operations (requires modification of the CMakeList.txt, out of my expertise)
- Break down the big GaitDS function to make it more understandable

**Comment by ThoChat** [comment]
This makes total sense.
However, let's not build everything from scratch.
As we need matrix operations, we'll have to work with the Eigen library.
This library already has an object called Vector3D that can be easily manipulated. 
Thus, I suggest we try to stick to using these to keep the code as close as possible to standards.
I already integrated the library into the Body-modeling-Xyioyun branch. I will try to replicate your changes in the branch using Eigen vectors and keep you updated about it.

**Comment by ThoChat** [comment]
Update of last modification on Body-modeling-Xyioyun branch:
- Integrate Eigen library dependency for matrix operation (require to install the library on your machine)
- Copy of the "HumanoidModelV0.cpp" from "Add-3D-point-support" branch, to have updated variables names
- Delete the support_foot parameter as the stepping_foot_index was similar, I addex this as comment: "-1 == right foot stepping/left foot support, 0 == double stance, 1 == left foot stepping/right foot support"


To do together:
- try to implement Vector3D for body point position

**Comment by ThoChat** [comment]
Question about the code:
- What is the variable "tmp"? Sometimes it's a vector (tmp = {feet_position[0], feet_position[1], feet_position[2], 1.0};) and then it's a double (tmp = 1 - update.step_timer/step_duration;)

Need to be tackled:
- Some variables are still difficult to identify ( example, in " p.center_of_mass = O18_0w;" what is "O18_0w"?)

Remaining problem:
- "RuntimeError: Point (2.0340437969715395, 1.6806476600896134) is outside of accessible area" This error is still there when running the "test_corridor.py". The problem is that the CoM (aka the position of the agents) is set to a value out of the walkable area of the simulation. I tracked the error until " p.center_of_mass = O18_0w;" and then the computation of O18_0w is too complicated to understand for me in its current state (more comment and variable renaming are required).

**Comment by ShangKaikai** [comment]
I have renamed some parameters in FuncMotion. Attached please find a file that illustrates the position corresponding to each coordinate like O3_0w. I hope it will help you understand FuncMotion. 

You may not need to fully understand FuncMotion, just knowing its inputs and outputs might be enough to use it. If needed, I can organize the code of FuncMotion with Eigen.

- "tmp" is just a short for "temporary". I have renamed all "tmp" in the FuncMotion

A problem

- I cant figure out why "lean_angle" always remains 0, even though it’s assigned a value of 2 in Line 747

btw, I’m not sure if it’s due to my campus network or VPN issues, but I’ve been having trouble pushing changes or viewing your commits this week, which didn't happen before. I'll test again this weekend with my home network.
Could you please leave a note here if you push any updates recently? This way, I'll know and check.
Million thanks!!!

[Explanations for FuncMotion.pptx](https://github.com/user-attachments/files/19499820/Explanations.for.FuncMotion.pptx)

**Comment by ThoChat** [comment]
Thanks for the changes!
And I just had a quick look at the presentation, but that looks like a big help too.


This problem is really weird, let's see if it continues.
I won't be pushing too much mush this week anyway.

I also still have a problem with the simulation that returns "Nan" for the output position of the agents... I'll investigate that next week. Do you have a similar problem or does it work on your side?

**Comment by ShangKaikai** [comment]
My home network works, so I think the problem is on my campus network.

On my side, the output in the terminal is like:
<img width="320" alt="Image" src="https://github.com/user-attachments/assets/3a0d4530-d43e-4fb0-9ab6-b78c53f74f64" />

How about you push your current version of the code, let's see if I could help.

**Comment by ThoChat** [comment]
I found the solution by removing some variables that were not assigned.
Yet, I'm not sure to understand why it worked for you and not me. Probably something to do with the compilation method.

Also, I pushed the modifications, but realised I built on top of your last commit. But I forgot to make a copy of the comments with the name of the body part in the "ANATOMY" list I asked you for last time... if you have the chance to had identify them again, that would be great.

**Comment by ShangKaikai** [comment]
Unfortunately, my campus network still not works, I can't pull your modifications, but I can check them on github. So far, I can only push or pull things with my home network.  I will work on the project on weekends, that's when I go home.

I have updated the explanation file. You can find all parameter's definitions here. 
Please let me know if u have any question.
[Explanations for FuncMotion.pptx](https://github.com/user-attachments/files/19665611/Explanations.for.FuncMotion.pptx)

**Comment by ThoChat** [comment]
Hi,
I've changed *FuncFootDH* and *FuncMotion* to use Eigen. However, the input and output still use std::array for now to integrate with the reste of the code.

Next steps I see now are: 
- Changing *GaitSS* to use Eigen too
- Changing inputs and outputs to minimise objctes manipulation (for Eigen to array and vice-vesa).
- Using *SCALING_FACTOR* defined in *HumanoidModelV0.hpp* instead of the ANATOMY list.

If you can think of anything else left to do before removing the *namespace*, please go ahead : )
And of course as always, feel free to ask anything!

**Comment by ShangKaikai** [comment]
Sounds great! let’s move on with your plan. 

Which part would you like me to handle?

Thanks!

**Comment by ShangKaikai** [comment]
Ok, I will work on the first item "Changing GaitSS to use Eigen too"

Maybe you can check the modifications on Monday

**Comment by ThoChat** [comment]
I think the branch is fine now. We still have to integrate the namespace in *HumanoidModelV0.cpp* into the model itself, but this will be done later on.
